### ISSUE TITLE
Request Specs

### ISSUE THREAD

**Issue by freddyrangel** [eliotsykes/rspec-rails-examples#43]
First of all, I love this resource! I've learned a thing or two. I work a ton in Rails APIs and I noticed there wasn't anything on request specs. I noticed a bit of discussion around that. I can submit a PR that adds that but I want to make sure such a PR would be welcome.

**Comment by eliotsykes** [comment]
Hi @freddyrangel and **thank you** sincerely for getting involved and your generous offer of a contribution. I've begun doing some (*admittedly* slow-moving) work on the API specs (and an API to test!). 

I'm treading a little carefully about exactly what's introduced to start with to make sure its a good stepping stone for what my students have learned prior to this. 

Once that foundation for writing API specs is in place and pushed, so there's something to build and improve on, I think that'd be the best time to make some request spec contributions. That might not be for a few weeks.

In the meantime, if you happen to know of or feel like contributing a request spec cheatsheet to link to from the README, that'd be a **hugely** valuable contribution that developers can start benefiting from sooner.

**Comment by freddyrangel** [comment]
Oh right on. That's a great idea. I'll get started on that then

**Comment by eliotsykes** [comment]
WIP: request specs, see #96

**Comment by eliotsykes** [comment]
Closed by #96
