### ISSUE TITLE
Model associations specs

### ISSUE THREAD

**Issue by amnesia7** [eliotsykes/rspec-rails-examples#67]
I was wondering if there was any chance of you fitting some associations into your spec examples somehow/somewhere so that we can see how best to handle specs for associations (`has_many` etc).

Thanks

**Comment by leesmith** [comment]
Check out shoulda-matchers ActiveRecord matchers:  http://matchers.shoulda.io/docs/v2.8.0/Shoulda/Matchers/ActiveRecord.html#have_many-instance_method

**Comment by amnesia7** [comment]
Ah ok. Thanks @leesmith
