### ISSUE TITLE
Upgrade to Rails Latest 4.2.x

### ISSUE THREAD

**Issue by eliotsykes** [eliotsykes/rspec-rails-examples#75]

**Comment by onebree** [comment]
I see that you want help. Is there anything in particular I can help with?

**Comment by eliotsykes** [comment]
Hi @onebree - thanks for the response. 

For this and any other help wanted issues in the project, its to flag improvements that I hope to be reasonably straightforward, and don't anticipate any problems with. If you're interested please feel free to contribute :+1:
